# Generated by Django 5.0.3 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="subscribe_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
