# Generated by Django 5.0.3 on 2024-03-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brandprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowerTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("insta_count", models.IntegerField()),
                ("fb_count", models.IntegerField()),
                (
                    "brand_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_follower_track",
                        to="brandprofile.brandprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "timestamp",
                "verbose_name_plural": "timestamps",
                "abstract": False,
            },
        ),
    ]
