# Generated by Django 5.0.3 on 2024-03-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followertrack", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followertrack",
            options={
                "verbose_name": "Follower Track",
                "verbose_name_plural": "Followers Track",
            },
        ),
    ]
