# Generated by Django 5.0.3 on 2024-03-22 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandprofile", "0001_initial"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratings",
            name="brand_user",
        ),
        migrations.AddField(
            model_name="ratings",
            name="brand_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brandprofile_rating",
                to="brandprofile.brandprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ratings",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
