# Generated by Django 5.0.3 on 2024-03-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandprofile", "0002_alter_brandprofile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brandprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
