# Generated by Django 5.0.3 on 2024-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandprofile", "0005_alter_brandprofile_email_alter_brandprofile_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
