# Generated by Django 5.0.3 on 2024-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brandprofile", "0006_alter_brandprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandprofile",
            name="facebook_followers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brandprofile",
            name="insta_followers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
