# Generated by Django 5.0.3 on 2024-04-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DraftProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("query", models.CharField(max_length=255)),
                ("brand_name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("insta", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("insta_followers", models.IntegerField(blank=True, null=True)),
                ("facebook_followers", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Draft Profiles",
            },
        ),
    ]
